create table CROS_CREDIT_MODEL(
    ID VARCHAR2(32) PRIMARY KEY,
    SERIAL_NO VARCHAR2(64),
    CHANNEL_NO VARCHAR2(16),
    PRODUCT_NO VARCHAR2(32),
    NAME VARCHAR2(60),
    IDCARD_TYPE VARCHAR2(2),
    IDCARD_NUM VARCHAR2(50),
    QUERY_REASON VARCHAR2(10),
    QUERY_TYPE VARCHAR2(10),
    RETURN_TYPE VARCHAR2(10),
    CREDIT_QUERY_STATE VARCHAR2(10),
    CREDIT_QUERY_TIME NUMBER(13),
    CREDIT_QUERY_FAIL_REASON VARCHAR2(2000),
    CROS_MODEL_QUERY_STATE VARCHAR2(10),
    CROS_MODEL_QUERY_TIME NUMBER(13),
    CROS_MODEL_FAIL_REASON VARCHAR2(2000),
    BUSINESS_PROCESS_STATE VARCHAR2(10),
    BUSINESS_PROCESS_TIME NUMBER(13),
    BUSINESS_PROCESS_NODE VARCHAR2(50),
    BUSINESS_PROCESS_FAIL_REASON VARCHAR2(2000),
    CREATA_TIME DATE,
    UPDATE_TIME DATE
);


COMMENT ON TABLE CROS_CREDIT_MODEL IS 'CROS-征信模型表';
COMMENT ON COLUMN CROS_CREDIT_MODEL.ID IS 'ID';
COMMENT ON COLUMN CROS_CREDIT_MODEL.SERIAL_NO IS '流水号';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CHANNEL_NO IS '渠道号(预留字段)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.PRODUCT_NO IS '产品号(预留字段)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.NAME IS '姓名';
COMMENT ON COLUMN CROS_CREDIT_MODEL.IDCARD_TYPE IS '证件类型:10(身份证号)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.IDCARD_NUM IS '证件号码';
COMMENT ON COLUMN CROS_CREDIT_MODEL.QUERY_REASON IS '查询原因:01(贷后管理);02(贷前审批)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.QUERY_TYPE IS '查询类型(非必输项):0(信用报告查询);1(信用报告查询)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.RETURN_TYPE IS '报文返回类型(非必输项):0(XML);1(HTML)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CREDIT_QUERY_STATE IS '征信查询状态';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CREDIT_QUERY_TIME IS '征信查询耗时(单位毫秒)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CREDIT_QUERY_FAIL_REASON IS '征信查询失败原因';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CROS_MODEL_QUERY_STATE IS 'CROS模型查询状态';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CROS_MODEL_QUERY_TIME IS 'CROS模型查询耗时(单位毫秒)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CROS_MODEL_FAIL_REASON IS 'CROS模型查询失败原因';
COMMENT ON COLUMN CROS_CREDIT_MODEL.BUSINESS_PROCESS_STATE IS '业务处理状态(成功或失败)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.BUSINESS_PROCESS_TIME IS '业务处理耗时(单位毫秒)';
COMMENT ON COLUMN CROS_CREDIT_MODEL.BUSINESS_PROCESS_NODE IS '业务处理节点';
COMMENT ON COLUMN CROS_CREDIT_MODEL.BUSINESS_PROCESS_FAIL_REASON IS '业务处理失败原因';
COMMENT ON COLUMN CROS_CREDIT_MODEL.CREATA_TIME IS '创建时间';
COMMENT ON COLUMN CROS_CREDIT_MODEL.UPDATE_TIME IS '更新时间';